apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-05T19:07:15Z"
  name: carts-canary
  resourceVersion: "15726"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 8706ff63-5f14-11ea-82aa-42010ab40002
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
